/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BidRouteImport } from './routes/bid'
import { Route as FameRouteImport } from './routes/fame'
import { Route as DoneBrandIdRouteImport } from './routes/done.$brandId'
import { Route as PayIntentIdRouteImport } from './routes/pay.$intentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BidRoute = BidRouteImport.update({
  id: '/bid',
  path: '/bid',
  getParentRoute: () => rootRouteImport,
} as any)
const FameRoute = FameRouteImport.update({
  id: '/fame',
  path: '/fame',
  getParentRoute: () => rootRouteImport,
} as any)
const DoneBrandIdRoute = DoneBrandIdRouteImport.update({
  id: '/done/$brandId',
  path: '/done/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIntentIdRoute = PayIntentIdRouteImport.update({
  id: '/pay/$intentId',
  path: '/pay/$intentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bid': typeof BidRoute
  '/fame': typeof FameRoute
  '/done/$brandId': typeof DoneBrandIdRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bid': typeof BidRoute
  '/fame': typeof FameRoute
  '/done/$brandId': typeof DoneBrandIdRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bid': typeof BidRoute
  '/fame': typeof FameRoute
  '/done/$brandId': typeof DoneBrandIdRoute
  '/pay/$intentId': typeof PayIntentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bid' | '/fame' | '/done/$brandId' | '/pay/$intentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bid' | '/fame' | '/done/$brandId' | '/pay/$intentId'
  id: '__root__' | '/' | '/bid' | '/fame' | '/done/$brandId' | '/pay/$intentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidRoute: typeof BidRoute
  FameRoute: typeof FameRoute
  DoneBrandIdRoute: typeof DoneBrandIdRoute
  PayIntentIdRoute: typeof PayIntentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bid': {
      id: '/bid'
      path: '/bid'
      fullPath: '/bid'
      preLoaderRoute: typeof BidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fame': {
      id: '/fame'
      path: '/fame'
      fullPath: '/fame'
      preLoaderRoute: typeof FameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/done/$brandId': {
      id: '/done/$brandId'
      path: '/done/$brandId'
      fullPath: '/done/$brandId'
      preLoaderRoute: typeof DoneBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$intentId': {
      id: '/pay/$intentId'
      path: '/pay/$intentId'
      fullPath: '/pay/$intentId'
      preLoaderRoute: typeof PayIntentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidRoute: BidRoute,
  FameRoute: FameRoute,
  DoneBrandIdRoute: DoneBrandIdRoute,
  PayIntentIdRoute: PayIntentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
